version: "3.2"
services:
  db:
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    networks:
      - creditNetwork
    environment:
      - MYSQL_ROOT_PASSWORD=dzvina1
      - MYSQL_DATABASE=CCP
      - MYSQL_USER=dzvina
      - MYSQL_PASSWORD=dzvina1
    ports:
      - 3306:3306
  credit:
      image: credit_ws
      networks:
        - creditNetwork
      depends_on:
        - db
        - customer
        - product
      ports:
        - 8081:8081
      environment:
        - DATABASE_HOST=db
        - DATABASE_USER=dzvina
        - DATABASE_PASSWORD=dzvina1
        - DATABASE_NAME=CCP
        - DATABASE_PORT=3306
  customer:
    image: customer_ws
    networks:
      - creditNetwork
    depends_on:
      - db
    ports:
      - 8082:8082
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=dzvina
      - DATABASE_PASSWORD=dzvina1
      - DATABASE_NAME=CCP
      - DATABASE_PORT=3306
  product:
    image: product_ws
    networks:
      - creditNetwork
    depends_on:
      - db
    ports:
      - 8083:8083
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=dzvina
      - DATABASE_PASSWORD=dzvina1
      - DATABASE_NAME=CCP
      - DATABASE_PORT=3306
networks:
  creditNetwork:


